export const GET_METHOD = 'GET'
export const POST_METHOD = 'POST'
export const PUT_METHOD = 'PUT'



// HR database
export const baseURL = 'http://51.158.191.94:3000/'
// export const baseURL = process.env.BACKEND || 'http://localhost:3000/'
export const userList = 'api/users/'
export const userDetail = 'api/users/'
export const userManager = 'api/users/manager/'
export const userName = 'api/users/name/'
export const teamList = 'api/teams/'
export const teamDetail = 'api/teams/'
export const teamManager = 'api/teams/manager/'
export const emp_att_detail = 'api/emp_att_detail/'
export const events = 'api/events/'
export const leaves = 'api/leaves/'
export const leaves_status = 'api/leaves/status/'
export const goalListEmp = 'api/goals/emp/'
export const goalListID = 'api/goals/'
export const goalUpdateID = 'api/goals/'
export const getWorkedHour = 'api/payroll_types/getHours/Worked'
// Machine Learning
export const baseURL_data = process.env.FLASK || 'http://127.0.0.1:5000/'

export const predict_attrition_id = 'predict_attrition/'
export const predict_fraud_id = 'predict_fraud/'

export const comparison_target_attrition = 'comparison_target_attrition'
export const comparison_predict_attrition = 'comparison_predict_attrition'
export const comparison_target_fraud = 'comparison_target_fraud'
export const comparison_predict_fraud = 'comparison_predict_fraud'

export const result_attrition = 'result_attrition'
export const result_fraud = 'result_fraud'


export const unseen_data ='unseen_data'
export const unseen_data_attrition ='unseen_data_attrition'
export const unseen_data_fraud ='unseen_data_fraud'
export const unseen_target_attrition ='unseen_target_attrition'
export const unseen_target_fraud ='unseen_target_fraud'
export const find_unseen_data ='find_unseen_data/'
export const find_unseen_data_attrition ='find_unseen_data_attrition/'
export const find_unseen_data_fraud ='find_unseen_data_fraud/'
export const find_unseen_target_attrition ='find_unseen_target_attrition/'
export const find_unseen_target_fraud ='find_unseen_target_fraud/'

export const age_distribution ='age_distribution'
export const education_field ='education_field'
export const gender_distribution ='gender_distribution'
export const marital_distribution ='marital_distribution'
export const distance_distribution ='distance_distribution'
export const department ='department'
export const business_travel ='busi_travel'
export const job_role ='job_role'
export const job_level ='job_level'
export const job_involve ='job_involve'
export const training_last_year ='training_lyear'
export const companies_worked ='companies_worked'
export const years_at_company ='ys_at_company'
export const years_in_current_role ='ys_in_role'
export const years_in_last_promotion ='ys_last_promotion'
export const total_work_years ='total_work_years'
export const years_with_curr_manager ='ys_curr_mana'
export const work_life_balance ='wo_li_bala'
export const over_time ='over_time'
export const monthly_income ='monthly_income'
export const percent_salary_hike ='percent_salary_hike'
export const stock_option_level ='stock_option_level'
export const env_satis ='env_satis'
export const job_satis ='job_satis'
export const relationship_satis ='relationship_satis'
export const performance_rating ='performance_rating'
export const columns_name ='get_columns_name'
export const get_data ='get_data'

